# Generated by Django 5.2.7 on 2025-11-02 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('RESPOND', 'Respond'), ('RESOLVE', 'Resolve')], max_length=50)),
                ('resource_type', models.CharField(choices=[('USER', 'User'), ('SERVICE', 'Service'), ('BOOKING', 'Booking'), ('CATEGORY', 'Category'), ('COMPLAINT', 'Complaint'), ('REVIEW', 'Review')], max_length=50)),
                ('resource_id', models.IntegerField()),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='api_adminac_admin_u_cf77e5_idx'), models.Index(fields=['resource_type', 'resource_id'], name='api_adminac_resourc_f5b633_idx')],
            },
        ),
    ]
