# Generated by Django 5.2.7 on 2025-11-17 15:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Service image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
