# Generated by Django 5.2.7 on 2025-11-30 10:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Optional notes from admin regarding payment verification', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_verified',
            field=models.BooleanField(default=False, help_text='Whether admin has verified the payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Screenshot of M-Pesa payment confirmation uploaded by seeker', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_payment_number',
            field=models.CharField(blank=True, help_text='M-Pesa number provided by the service provider', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('M_PESA', 'M-Pesa'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer')], default='M_PESA', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_VERIFICATION', 'Pending Verification'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=50),
        ),
    ]
