# Generated by Django 5.2.7 on 2025-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_mpesa_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MOBILE_MONEY', 'Mobile Money (M-Pesa)'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card')], help_text="Payment method for this service (uses provider's default if not set)", max_length=50, null=True),
        ),
    ]
