# Generated by Django 5.2.7 on 2025-11-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Enable email notifications for bookings and services'),
        ),
    ]
