# Generated by Django 5.2.7 on 2025-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Address', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_contact_info',
            field=models.BooleanField(default=False, help_text='Allow providers to see contact info in booking details'),
        ),
    ]
