# Generated by Django 5.2.7 on 2025-11-17 16:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_address_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='User profile image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
