# Generated by Django 5.2.7 on 2025-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provider_payment_method',
            field=models.CharField(blank=True, choices=[('MOBILE_MONEY', 'Mobile Money (M-Pesa)'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card')], default='MOBILE_MONEY', help_text='Default payment method for provider', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='provider_payment_number',
            field=models.CharField(blank=True, help_text='Default payment number for provider (e.g., M-Pesa number)', max_length=50, null=True),
        ),
    ]
